// Copyright 2026 github.com/mixcode

package binarystruct_test

import "testing"

// TestCodegen_BatchScalars_Parity exercises the default scalar-field batching:
// a run of ≥2 contiguous fixed-width scalar fields is coalesced into one buffer +
// a single Write/ReadFull. It asserts the generated bytes are identical to the
// runtime interpreter (so batching preserves layout/endianness/width) and that
// the round trip recovers the value — for an all-scalar header AND a mixed struct
// where an array field breaks the run into two separate batches.
func TestCodegen_BatchScalars_Parity(t *testing.T) {
	typesSrc := "type Header struct {\n" +
		"\t_ struct{} `binary:\"endian=big\"`\n" +
		"\tA uint8   `binary:\"uint8\"`\n" +
		"\tB int16   `binary:\"int16\"`\n" +
		"\tC uint32  `binary:\"uint32\"`\n" +
		"\tD int64   `binary:\"int64\"`\n" +
		"\tE float32 `binary:\"float32\"`\n" +
		"\tF float64 `binary:\"float64\"`\n}\n" +
		"type Mixed struct {\n" +
		"\t_    struct{} `binary:\"endian=big\"`\n" +
		"\tA    uint32   `binary:\"uint32\"`\n" +
		"\tB    uint16   `binary:\"uint16\"`\n" +
		"\tName [4]byte  `binary:\"[4]byte\"`\n" +
		"\tC    uint64   `binary:\"uint64\"`\n" +
		"\tD    int32    `binary:\"int32\"`\n}\n" +
		// Guarded: a range-validated field sits between batchable scalars. It must
		// NOT be swallowed into a batch (which would skip decode validation).
		"type Guarded struct {\n" +
		"\t_ struct{} `binary:\"endian=big\"`\n" +
		"\tA uint16   `binary:\"uint16\"`\n" +
		"\tV uint8    `binary:\"uint8,range=0..10\"`\n" +
		"\tB uint16   `binary:\"uint16\"`\n}\n"

	testSrc := "import (\n\t\"bytes\"\n\t\"errors\"\n\t\"testing\"\n\n\t\"github.com/mixcode/binarystruct\"\n)\n\n" +
		"func TestBatch(t *testing.T) {\n" +
		"\th := Header{A: 1, B: -2, C: 0x01020304, D: -4, E: 1.5, F: -2.25}\n" +
		"\tgen, err := h.MarshalBinary()\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n" +
		"\trt, err := binarystruct.Marshal(&h) // runtime interpreter\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n" +
		"\tif !bytes.Equal(gen, rt) {\n\t\tt.Fatalf(\"Header codegen %x vs runtime %x\", gen, rt)\n\t}\n" +
		"\tvar ho Header\n\tif err := ho.UnmarshalBinary(gen); err != nil {\n\t\tt.Fatal(err)\n\t}\n" +
		"\tif ho != h {\n\t\tt.Fatalf(\"Header round trip: got %+v want %+v\", ho, h)\n\t}\n" +
		// AppendBinary delegates to the same batched WriteBinary, so it must produce
		// identical bytes (appended onto an existing prefix).
		"\tab, err := h.AppendBinary([]byte{0xAA})\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n" +
		"\tif !bytes.Equal(ab, append([]byte{0xAA}, gen...)) {\n\t\tt.Fatalf(\"AppendBinary %x != 0xAA + MarshalBinary %x\", ab, gen)\n\t}\n" +
		"\tmx := Mixed{A: 0x01020304, B: 0x0506, Name: [4]byte{'a', 'b', 'c', 'd'}, C: 0xdeadbeef, D: -9}\n" +
		"\tgen2, err := mx.MarshalBinary()\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n" +
		"\trt2, err := binarystruct.Marshal(&mx)\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n" +
		"\tif !bytes.Equal(gen2, rt2) {\n\t\tt.Fatalf(\"Mixed codegen %x vs runtime %x\", gen2, rt2)\n\t}\n" +
		"\tvar mo Mixed\n\tif err := mo.UnmarshalBinary(gen2); err != nil {\n\t\tt.Fatal(err)\n\t}\n" +
		"\tif mo != mx {\n\t\tt.Fatalf(\"Mixed round trip: got %+v want %+v\", mo, mx)\n\t}\n" +
		// Guarded: valid value round-trips; a range field between scalars must still
		// be validated on decode (not skipped by batching).
		"\tgv := Guarded{A: 1, V: 5, B: 2}\n" +
		"\tgb, err := gv.MarshalBinary()\n\tif err != nil {\n\t\tt.Fatal(err)\n\t}\n" +
		"\tvar go1 Guarded\n\tif err := go1.UnmarshalBinary(gb); err != nil {\n\t\tt.Fatal(err)\n\t}\n" +
		"\tif go1 != gv {\n\t\tt.Fatalf(\"Guarded round trip: got %+v want %+v\", go1, gv)\n\t}\n" +
		"\tgb[2] = 0xFF // V is at offset 2 (after A uint16); out of range 0..10\n" +
		"\tvar go2 Guarded\n\tif err := go2.UnmarshalBinary(gb); err == nil {\n\t\tt.Fatal(\"expected a range validation error on V; batching must not skip it\")\n\t} else if !errors.Is(err, binarystruct.ErrValidationError) {\n\t\tt.Fatalf(\"want ErrValidationError, got %v\", err)\n\t}\n}\n"

	genBytelenCase(t, "p", typesSrc, "Header,Mixed,Guarded", testSrc)
}
