// Copyright 2021 github.com/mixcode

package binarystruct

import (
	"bytes"
	stdencoding "encoding"
	"fmt"
	"io"
	"math"
	"reflect"

	"golang.org/x/text/encoding"
)

// Marshal encodes a go value into binary data and return it as []byte.
func Marshal(govalue interface{}, order ByteOrder) (encoded []byte, err error) {
	var ms Marshaller
	return (&ms).Marshal(govalue, order)
}

// Write encodes a go value into binary stream and writes to w.
func Write(w io.Writer, order ByteOrder, govalue interface{}) (n int, err error) {
	var ms Marshaller
	return (&ms).Write(w, order, govalue)
}

// MarshalAs encodes a go value into binary data using the supplied tag and returns it as []byte.
func MarshalAs(govalue interface{}, tag string, order ByteOrder) (encoded []byte, err error) {
	var ms Marshaller
	return (&ms).MarshalAs(govalue, tag, order)
}

// WriteAs encodes a go value into a binary stream using the supplied tag and writes it to w.
func WriteAs(w io.Writer, tag string, order ByteOrder, govalue interface{}) (n int, err error) {
	var ms Marshaller
	return (&ms).WriteAs(w, tag, order, govalue)
}

// Marshaller is go-type to binary-type encoder with environmental values
type Marshaller struct {
	TextEncoding        map[string]encoding.Encoding // map[encodingName]Encoding
	DefaultTextEncoding string                       // default text encoding name
	serializers         map[string]Serializer        // registered custom serializers

	encoderCache map[string]*encoding.Encoder // cache of encoding.NewEncoder()
	decoderCache map[string]*encoding.Decoder // cache of encoding.NewDecoder()
}

// AddTextEncoding set a new text encoder to a Marshaller.
// Provided encodingName could be used in string tag's 'encoding' property, like `binary:"string,encoding=encodingName"`
func (ms *Marshaller) AddTextEncoding(encodingName string, enc encoding.Encoding) {
	if ms.TextEncoding == nil {
		ms.TextEncoding = make(map[string]encoding.Encoding)
	}
	ms.TextEncoding[encodingName] = enc
}

// RemoveTextEncoding removes an encoding from a Marshaller.
func (ms *Marshaller) RemoveTextEncoding(encodingName string) {
	if ms.TextEncoding != nil {
		delete(ms.TextEncoding, encodingName)
	}
	if ms.encoderCache != nil {
		delete(ms.encoderCache, encodingName)
	}
	if ms.decoderCache != nil {
		delete(ms.decoderCache, encodingName)
	}
}

// AddSerializer registers a custom Serializer with a Marshaller.
// Provided name could be used in struct field tags, like `binary:"...,serializer=name"`
func (ms *Marshaller) AddSerializer(name string, s Serializer) {
	if ms.serializers == nil {
		ms.serializers = make(map[string]Serializer)
	}
	ms.serializers[name] = s
}

// RemoveSerializer removes a registered custom Serializer.
func (ms *Marshaller) RemoveSerializer(name string) {
	if ms.serializers != nil {
		delete(ms.serializers, name)
	}
}

// GetSerializer returns a registered custom Serializer by name, or nil if not found.
// This method is used by code generated by the codegen tool to look up serializers at runtime.
func (ms *Marshaller) GetSerializer(name string) Serializer {
	if ms.serializers != nil {
		if s, ok := ms.serializers[name]; ok {
			return s
		}
	}
	return nil
}

// Marshaller.Marshal() is binary image encoder with environment in a Marshaller.
func (ms *Marshaller) Marshal(govalue interface{}, order ByteOrder) (encoded []byte, err error) {
	var b bytes.Buffer
	_, err = ms.Write(&b, order, govalue)
	return b.Bytes(), err
}

// Marshaller.MarshalAs() is binary image encoder with environment in a Marshaller using the supplied tag.
func (ms *Marshaller) MarshalAs(govalue interface{}, tag string, order ByteOrder) (encoded []byte, err error) {
	var b bytes.Buffer
	_, err = ms.WriteAs(&b, tag, order, govalue)
	return b.Bytes(), err
}

// Marshaller.Write() is binary stream encoder with environment in a Marshaller.
func (ms *Marshaller) Write(w io.Writer, order ByteOrder, data interface{}) (n int, err error) {
	return ms.writeValue(w, order, reflect.ValueOf(data))
}

// Marshaller.WriteAs() is binary stream encoder with environment in a Marshaller using the supplied tag.
func (ms *Marshaller) WriteAs(w io.Writer, tag string, order ByteOrder, data interface{}) (n int, err error) {
	v := reflect.ValueOf(data)
	t := v.Type()
	k := t.Kind()
	for k == reflect.Ptr || k == reflect.Interface {
		v = reflect.Indirect(v)
		t = v.Type()
		k = t.Kind()
	}

	var fieldErr error
	switch k {
	case reflect.Invalid:
		fieldErr = fmt.Errorf("invalid data type")
	case reflect.Complex64, reflect.Complex128:
		fieldErr = fmt.Errorf("complex type not supported")
	case reflect.UnsafePointer:
		fieldErr = fmt.Errorf("pointer type not supported")
	case reflect.Chan, reflect.Func, reflect.Map:
		fieldErr = fmt.Errorf("unsupported type: %v", k)
	}

	naturalType, naturalOption := getNaturalType(v)
	encodeType, option, err := parseTagString(tag, reflect.Value{}, naturalType, naturalOption, fieldErr)
	if err != nil {
		return 0, err
	}

	return ms.writeMain(w, order, v, encodeType, option, reflect.Value{}, -1)
}

// write a reflect.Value
func (ms *Marshaller) writeValue(w io.Writer, order ByteOrder, v reflect.Value) (n int, err error) {
	t := v.Type()
	k := t.Kind()
	for k == reflect.Ptr || k == reflect.Interface {
		v = reflect.Indirect(v)
		t = v.Type()
		k = t.Kind()
	}
	encodeType, option := getNaturalType(v)

	return ms.writeMain(w, order, v, encodeType, option, reflect.Value{}, -1)
}

// write a value as given type
func (ms *Marshaller) writeMain(w io.Writer, order ByteOrder, v reflect.Value, encodeType eType, option typeOption, parentStruct reflect.Value, fieldIndex int) (n int, err error) {

	order = resolveByteOrder(order, option.endian)

	if option.serializer != "" {
		serializer, ok := ms.serializers[option.serializer]
		if !ok {
			return 0, fmt.Errorf("unknown serializer: %s", option.serializer)
		}
		return serializer.Serialize(w, v.Interface(), parentStruct, fieldIndex, order)
	}

	if encodeType == Any {
		var naturalOption typeOption
		encodeType, naturalOption = getNaturalType(v)
		option.indirectCount += naturalOption.indirectCount
	}

	// type was a pointer or an interface
	if option.indirectCount > 0 {
		for i := 0; i < option.indirectCount; i++ {
			v = v.Elem()
		}
	}

	if option.isArray {
		// write the array
		if option.arrayLen == 0 {
			return
		}
		return ms.writeArray(w, order, v, encodeType, option)
	}

	// based on individual type
	switch encodeType {

	case iStruct:
		return ms.writeStruct(w, order, v)

	case Pad: // padding zero bytes: `binary:"pad(10)"`
		l := option.bufLen
		if l == 0 {
			l = 1
		}
		return zeroFill(w, l)

	case Ignore: // ignoring value: `binary:"ignore"`
		return 0, nil

	case iInvalid:
		err = ErrInvalidType
		return
	}

	// based on kind group
	switch encodeType.iKind() {

	case intKind, uintKind, bitmapKind, floatKind:
		return ms.writeScalar(w, order, v, encodeType)

	case structKind:
		return ms.writeStruct(w, order, v)

	case stringKind:
		return ms.writeString(w, order, v, encodeType, option.bufLen, option.encoding)
	}

	err = fmt.Errorf("unknown type %s", encodeType)
	return
}

// write an array
func (ms *Marshaller) writeArray(w io.Writer, order ByteOrder, array reflect.Value, elementType eType, option typeOption) (n int, err error) {

	arrayKind := array.Kind()
	//
	// Go arrays and slices are primary target of array notation.
	//	a []int	`binary:"[10]byte"`
	// And there is a special case for string.
	//	s string `binary:"[10]uint16"`	// each string byte is converted to uint16
	// An exceptional case is that the target type is string array and given value is a string.
	//	s string `binary:"[3]zstring(0x10)"`	// s is writen as first string, and the others will be blank string
	//
	if arrayKind == reflect.String && elementType.iKind() != stringKind {
		// convert string to byte slice
		array = array.Convert(byteSliceType)
		arrayKind = array.Kind()
	}

	arrayLen := 1
	if arrayKind == reflect.Array || arrayKind == reflect.Slice {
		arrayLen = array.Len()
	}

	desiredLen := option.arrayLen
	if desiredLen <= 0 {
		desiredLen = arrayLen
	}
	if desiredLen < arrayLen {
		err = fmt.Errorf("array too large to fit: len %d, size %d", desiredLen, arrayLen)
		return
		// arrayLen = desiredLen
	}

	wErr := func(i int, e error) error {
		return fmt.Errorf("array index [%d]: %w", i, e)
	}
	var m int
	for i := 0; i < arrayLen; i++ {
		var e reflect.Value
		if arrayKind == reflect.Array || arrayKind == reflect.Slice {
			e = array.Index(i)
		} else {
			e = array
		}
		if elementType == Any {
			m, err = ms.writeValue(w, order, e)
			if err != nil {
				err = wErr(i, err)
				return
			}
		} else {
			var o typeOption
			o.bufLen = option.bufLen     // option may contain inheritable values
			o.encoding = option.encoding // option may contain inheritable values
			m, err = ms.writeMain(w, order, e, elementType, o, reflect.Value{}, -1)
			if err != nil {
				err = wErr(i, err)
				return
			}
		}
		n += m
	}
	if arrayLen < desiredLen {
		// fill the leftover
		sz := option.bufLen // element length supplied
		if sz == 0 {
			sz = m // m holds the byte count of last written element
		}
		if sz == 0 {
			// guess byte size of the element type
			eType := array.Elem().Type()
			eKind := eType.Kind()
			for eKind == reflect.Ptr || eKind == reflect.Interface {
				eType = eType.Elem()
				eKind = eType.Kind()
			}
			sz = int(eType.Size())
		}

		// total size = element size * element count
		sz = sz * (desiredLen - arrayLen)

		// write blank bytes
		m, err = zeroFill(w, sz)
		n += m
		if err != nil {
			return
		}
	}
	return
}

// write a struct
func (ms *Marshaller) writeStruct(w io.Writer, order ByteOrder, strc reflect.Value) (n int, err error) {
	if strc.CanInterface() {
		val := strc.Interface()
		if mw, ok := val.(MarshallerContextWriter); ok {
			return mw.WriteBinaryWithMarshaller(ms, w, order)
		}
		if bw, ok := val.(BinaryWriter); ok {
			return bw.WriteBinary(w, order)
		}
		if bm, ok := val.(stdencoding.BinaryMarshaler); ok {
			var blob []byte
			blob, err = bm.MarshalBinary()
			if err != nil {
				return 0, err
			}
			return w.Write(blob)
		}
	}
	if strc.CanAddr() {
		addr := strc.Addr()
		if addr.CanInterface() {
			val := addr.Interface()
			if mw, ok := val.(MarshallerContextWriter); ok {
				return mw.WriteBinaryWithMarshaller(ms, w, order)
			}
			if bw, ok := val.(BinaryWriter); ok {
				return bw.WriteBinary(w, order)
			}
			if bm, ok := val.(stdencoding.BinaryMarshaler); ok {
				var blob []byte
				blob, err = bm.MarshalBinary()
				if err != nil {
					return 0, err
				}
				return w.Write(blob)
			}
		}
	}

	if !safeMode {
		return ms.unsafeWriteStruct(w, order, strc)
	}
	typ := strc.Type()
	meta, err := getStructMetadata(typ)
	if err != nil {
		return 0, err
	}
	wErr := func(i int, e error) error {
		f := typ.Field(i)
		return fmt.Errorf("field <%s>: %w", f.Name, e)
	}
	for _, fMeta := range meta.fields {
		if fMeta.ignore {
			continue
		}
		if fMeta.unexported {
			continue
		}
		if fMeta.fieldErr != nil && !fMeta.hasTag {
			err = wErr(fMeta.index, fMeta.fieldErr)
			return
		}

		fieldVal := strc.Field(fMeta.index)

		if fMeta.omittable {
			if fMeta.omittableExpr != "" {
				limit, errEval := evaluateTagValue(strc, fMeta.omittableExpr)
				if errEval == nil && n >= limit {
					break
				}
			}
			fKind := typ.Field(fMeta.index).Type.Kind()
			if (fKind == reflect.Ptr || fKind == reflect.Interface) && fieldVal.IsNil() {
				break
			}
		}

		var naturalType eType
		var option typeOption
		if fieldVal.IsValid() {
			naturalType, option = getNaturalType(fieldVal)
		}

		if fMeta.hasTag {
			if naturalType == iInvalid && (fMeta.encodeType != Pad && fMeta.encodeType != Ignore) {
				if fMeta.fieldErr != nil {
					err = wErr(fMeta.index, fMeta.fieldErr)
				} else {
					err = wErr(fMeta.index, fmt.Errorf("the field %s is not encodable", fMeta.name))
				}
				return
			}
			if fMeta.encodeType != Any {
				naturalType = fMeta.encodeType
			}
			if fMeta.isArray {
				option.isArray = true
				if fMeta.arrayLenExpr != "" {
					option.arrayLen, err = evaluateTagValue(strc, fMeta.arrayLenExpr)
					if err != nil {
						err = wErr(fMeta.index, err)
						return
					}
					if option.arrayLen < 0 {
						err = wErr(fMeta.index, errNegativeSize)
						return
					}
				}
			}
			if fMeta.bufLenExpr != "" {
				option.bufLen, err = evaluateTagValue(strc, fMeta.bufLenExpr)
				if err != nil {
					err = wErr(fMeta.index, err)
					return
				}
				if option.bufLen < 0 {
					err = wErr(fMeta.index, errNegativeSize)
					return
				}
			}
			if fMeta.encoding != "" {
				option.encoding = fMeta.encoding
			}
			if fMeta.endian != endianNone {
				option.endian = fMeta.endian
			}
			if fMeta.serializer != "" {
				option.serializer = fMeta.serializer
			}
		}

		var m int
		m, err = ms.writeMain(w, order, fieldVal, naturalType, option, strc, fMeta.index)
		if err != nil {
			err = wErr(fMeta.index, err)
			return
		}
		n += m
	}
	return
}

// EncodeText encodes a string with installed encoding.
func (ms *Marshaller) EncodeText(utf8 []byte, textEncoding string) (encoded []byte, err error) {
	if textEncoding == "" {
		encoded = utf8
		return
	}
	var ec *encoding.Encoder
	if ms.encoderCache != nil {
		ec = ms.encoderCache[textEncoding]
	}
	if ec == nil {
		if ms.TextEncoding != nil {
			ec = ms.TextEncoding[textEncoding].NewEncoder()
		}
		if ec == nil {
			err = fmt.Errorf("unknown text encoding %s", textEncoding)
			return
		}
		if ms.encoderCache == nil {
			ms.encoderCache = make(map[string]*encoding.Encoder)
		}
		ms.encoderCache[textEncoding] = ec
	}
	return ec.Bytes(utf8)
}

// DecodeText decodes a string with installed encoding.
func (ms *Marshaller) DecodeText(encoded []byte, textEncoding string) (utf8 []byte, err error) {
	if textEncoding == "" {
		utf8 = encoded
		return
	}
	var dc *encoding.Decoder
	if ms.decoderCache != nil {
		dc = ms.decoderCache[textEncoding]
	}
	if dc == nil {
		if ms.TextEncoding != nil {
			dc = ms.TextEncoding[textEncoding].NewDecoder()
		}
		if dc == nil {
			err = fmt.Errorf("unknown text encoding %s", textEncoding)
			return
		}
		if ms.decoderCache == nil {
			ms.decoderCache = make(map[string]*encoding.Decoder)
		}
		ms.decoderCache[textEncoding] = dc
	}
	return dc.Bytes(encoded)
}

// write string types
func (ms *Marshaller) writeString(w io.Writer, order ByteOrder, v reflect.Value, encodeType eType, bufLen int, textEncoding string) (n int, err error) {
	s := v.String()
	stringBytes := []byte(s)

	var m int

	// process text encoding
	if textEncoding == "" {
		textEncoding = ms.DefaultTextEncoding
	}
	if textEncoding != "" {
		stringBytes, err = ms.EncodeText(stringBytes, textEncoding)
		if err != nil {
			return
		}
	}

	strlen := len(stringBytes)
	if bufLen <= 0 {
		bufLen = strlen
	}
	if bufLen < strlen {
		err = fmt.Errorf("string too long: len %d, buffer size %d", strlen, bufLen)
		return
	}

	// write string length
	maxlen, headersz := uint64(math.MaxInt64), 0
	switch encodeType {
	case Bstring:
		maxlen, headersz = math.MaxUint8, 1
	case Wstring:
		maxlen, headersz = math.MaxUint16, 2
	case Dwstring:
		maxlen, headersz = math.MaxUint32, 4
	}
	if uint64(bufLen) > maxlen {
		err = fmt.Errorf("string too long: len %d, max %d", strlen, maxlen)
		return
	}

	if headersz > 0 {
		// write string size header
		m, err = writeU64(w, order, uint64(strlen), headersz)
		n += m
		if err != nil {
			return
		}
	}

	// write string bytes
	m, err = w.Write(stringBytes)
	n += m
	if err != nil {
		return
	}

	// write terminating zero
	switch encodeType {
	case Zstring:
		w.Write(terminatingZeros[:1])
		n += 1
		m += 1
	case Z16string:
		w.Write(terminatingZeros[:2])
		n += 2
		m += 2
		//case Z32string:
		//	w.Write(terminatingZeros[:4])
	}

	if m < bufLen {
		// fill the leftovers
		m, err = zeroFill(w, bufLen-m)
		n += m
		if err != nil {
			return
		}
		return
	}

	return
}

// write a scalar value
func (ms *Marshaller) writeScalar(w io.Writer, order ByteOrder, v reflect.Value, k eType) (n int, err error) {
	enc := encodeFunc(v.Type(), k)
	if enc == nil {
		err = ErrInvalidType
		return
	}
	u64, sz, err := enc(v)
	if err != nil {
		return
	}
	return writeU64(w, order, u64, sz)
}

// write bytes according to the byte order
func writeU64(w io.Writer, order ByteOrder, u64 uint64, bytesize int) (n int, err error) {
	var buf [8]byte
	b := buf[:bytesize]
	switch bytesize {
	case 1:
		b[0] = byte(u64)
	case 2:
		order.PutUint16(b, uint16(u64))
	case 4:
		order.PutUint32(b, uint32(u64))
	case 8:
		order.PutUint64(b, u64)
	default:
		panic("invalid byte size")
	}
	return w.Write(b)
}

// write blank padding bytes
func zeroFill(w io.Writer, sz int) (n int, err error) {
	maxBufSize := 16384
	bsz := sz
	if bsz > maxBufSize {
		bsz = maxBufSize
	}
	buf := make([]byte, bsz)
	var m int
	for sz > 0 {
		if sz > maxBufSize {
			m, err = w.Write(buf)
		} else {
			m, err = w.Write(buf[:sz])
		}
		n += m
		sz -= m
		if err != nil {
			return
		}
	}
	return
}

var (
	terminatingZeros = []byte{0, 0, 0, 0}
)

// BinaryWriter is implemented by types that can serialize themselves to a stream.
type BinaryWriter interface {
	WriteBinary(w io.Writer, order ByteOrder) (int, error)
}

// MarshallerContextWriter is implemented by types that can serialize themselves to a stream using a Marshaller context.
type MarshallerContextWriter interface {
	WriteBinaryWithMarshaller(ms *Marshaller, w io.Writer, order ByteOrder) (int, error)
}
