// Copyright 2021 github.com/mixcode

package binarystruct

import (
	"bytes"
	stdencoding "encoding"
	"fmt"
	"io"
	"math"
	"reflect"

	"golang.org/x/text/encoding"
)

// Marshal encodes a go value into binary data and return it as []byte.
func Marshal(govalue interface{}, order ByteOrder) (encoded []byte, err error) {
	return NewMarshaler(order).Marshal(govalue)
}

// Write encodes a go value into binary stream and writes to w.
func Write(w io.Writer, order ByteOrder, govalue interface{}) (n int, err error) {
	return NewMarshaler(order).Write(w, govalue)
}

// MarshalAs encodes a go value into binary data using the supplied tag and returns it as []byte.
func MarshalAs(govalue interface{}, tag string, order ByteOrder) (encoded []byte, err error) {
	return NewMarshaler(order).MarshalAs(govalue, tag)
}

// WriteAs encodes a go value into a binary stream using the supplied tag and writes it to w.
func WriteAs(w io.Writer, tag string, order ByteOrder, govalue interface{}) (n int, err error) {
	return NewMarshaler(order).WriteAs(w, tag, govalue)
}

// Marshaler is go-type to binary-type encoder/decoder with environmental values.
// The byte order is part of the Marshaler: set it with NewMarshaler (or the Order
// field) once, and the Marshal/Unmarshal/Write/Read methods no longer take an
// order argument. A per-field `endian=` tag still overrides it for that field.
type Marshaler struct {
	Order               ByteOrder                    // byte order used by the methods; set via NewMarshaler
	TextEncoding        map[string]encoding.Encoding // map[encodingName]Encoding
	DefaultTextEncoding string                       // default text encoding name
	serializers         map[string]Serializer        // registered custom serializers

	encoderCache map[string]*encoding.Encoder // cache of encoding.NewEncoder()
	decoderCache map[string]*encoding.Decoder // cache of encoding.NewDecoder()
}

// NewMarshaler returns a Marshaler that encodes and decodes using the given byte
// order. The order may be overridden per field with the `endian=` struct tag.
func NewMarshaler(order ByteOrder) *Marshaler {
	return &Marshaler{Order: order}
}

// effectiveOrder returns the Marshaler's byte order, or an error if none was set
// (e.g. a zero-value Marshaler{} that skipped NewMarshaler and left Order nil).
func (ms *Marshaler) effectiveOrder() (ByteOrder, error) {
	if ms.Order == nil {
		return nil, fmt.Errorf("binarystruct: no byte order set; use NewMarshaler(order) or set the Marshaler.Order field")
	}
	return ms.Order, nil
}

// AddTextEncoding set a new text encoder to a Marshaler.
// Provided encodingName could be used in string tag's 'encoding' property, like `binary:"string,encoding=encodingName"`
func (ms *Marshaler) AddTextEncoding(encodingName string, enc encoding.Encoding) {
	if ms.TextEncoding == nil {
		ms.TextEncoding = make(map[string]encoding.Encoding)
	}
	ms.TextEncoding[encodingName] = enc
}

// RemoveTextEncoding removes an encoding from a Marshaler.
func (ms *Marshaler) RemoveTextEncoding(encodingName string) {
	if ms.TextEncoding != nil {
		delete(ms.TextEncoding, encodingName)
	}
	if ms.encoderCache != nil {
		delete(ms.encoderCache, encodingName)
	}
	if ms.decoderCache != nil {
		delete(ms.decoderCache, encodingName)
	}
}

// AddSerializer registers a custom Serializer with a Marshaler.
// Provided name could be used in struct field tags, like `binary:"...,serializer=name"`
func (ms *Marshaler) AddSerializer(name string, s Serializer) {
	if ms.serializers == nil {
		ms.serializers = make(map[string]Serializer)
	}
	ms.serializers[name] = s
}

// RemoveSerializer removes a registered custom Serializer.
func (ms *Marshaler) RemoveSerializer(name string) {
	if ms.serializers != nil {
		delete(ms.serializers, name)
	}
}

// GetSerializer returns a registered custom Serializer by name, or nil if not found.
// This method is used by code generated by the codegen tool to look up serializers at runtime.
func (ms *Marshaler) GetSerializer(name string) Serializer {
	if ms.serializers != nil {
		if s, ok := ms.serializers[name]; ok {
			return s
		}
	}
	return nil
}

// Marshaler.Marshal() encodes a go value into binary data using the Marshaler's byte order.
func (ms *Marshaler) Marshal(govalue interface{}) (encoded []byte, err error) {
	var b bytes.Buffer
	_, err = ms.Write(&b, govalue)
	return b.Bytes(), err
}

// Marshaler.MarshalAs() encodes a go value using the supplied tag and the Marshaler's byte order.
func (ms *Marshaler) MarshalAs(govalue interface{}, tag string) (encoded []byte, err error) {
	var b bytes.Buffer
	_, err = ms.WriteAs(&b, tag, govalue)
	return b.Bytes(), err
}

// Marshaler.Write() encodes a go value into a binary stream using the Marshaler's byte order.
func (ms *Marshaler) Write(w io.Writer, data interface{}) (n int, err error) {
	order, err := ms.effectiveOrder()
	if err != nil {
		return 0, err
	}
	return ms.writeValue(w, order, reflect.ValueOf(data))
}

// Marshaler.WriteAs() encodes a go value into a binary stream using the supplied tag and the Marshaler's byte order.
func (ms *Marshaler) WriteAs(w io.Writer, tag string, data interface{}) (n int, err error) {
	order, err := ms.effectiveOrder()
	if err != nil {
		return 0, err
	}
	v := reflect.ValueOf(data)
	t := v.Type()
	k := t.Kind()
	for k == reflect.Ptr || k == reflect.Interface {
		v = reflect.Indirect(v)
		t = v.Type()
		k = t.Kind()
	}

	var fieldErr error
	switch k {
	case reflect.Invalid:
		fieldErr = fmt.Errorf("invalid data type")
	case reflect.Complex64, reflect.Complex128:
		fieldErr = fmt.Errorf("complex type not supported")
	case reflect.UnsafePointer:
		fieldErr = fmt.Errorf("pointer type not supported")
	case reflect.Chan, reflect.Func, reflect.Map:
		fieldErr = fmt.Errorf("unsupported type: %v", k)
	}

	naturalType, naturalOption := getNaturalType(v)
	encodeType, option, err := parseTagString(tag, reflect.Value{}, naturalType, naturalOption, fieldErr)
	if err != nil {
		return 0, err
	}

	return ms.writeMain(w, order, v, encodeType, option, reflect.Value{}, -1)
}

// write a reflect.Value
func (ms *Marshaler) writeValue(w io.Writer, order ByteOrder, v reflect.Value) (n int, err error) {
	t := v.Type()
	k := t.Kind()
	for k == reflect.Ptr || k == reflect.Interface {
		v = reflect.Indirect(v)
		t = v.Type()
		k = t.Kind()
	}
	encodeType, option := getNaturalType(v)

	return ms.writeMain(w, order, v, encodeType, option, reflect.Value{}, -1)
}

// write a value as given type
func (ms *Marshaler) writeMain(w io.Writer, order ByteOrder, v reflect.Value, encodeType eType, option typeOption, parentStruct reflect.Value, fieldIndex int) (n int, err error) {

	order = resolveByteOrder(order, option.endian)

	if option.serializer != "" {
		serializer, ok := ms.serializers[option.serializer]
		if !ok {
			return 0, fmt.Errorf("unknown serializer: %s", option.serializer)
		}
		return serializer.Serialize(w, v.Interface(), parentStruct, fieldIndex, order)
	}

	if encodeType == Any {
		var naturalOption typeOption
		encodeType, naturalOption = getNaturalType(v)
		option.indirectCount += naturalOption.indirectCount
	}

	// type was a pointer or an interface
	if option.indirectCount > 0 {
		for i := 0; i < option.indirectCount; i++ {
			v = v.Elem()
		}
	}

	if option.isArray {
		// write the array
		if option.arrayLen == 0 {
			return
		}
		return ms.writeArray(w, order, v, encodeType, option)
	}

	// based on individual type
	switch encodeType {

	case iStruct:
		return ms.writeStruct(w, order, v)

	case Pad: // padding zero bytes: `binary:"pad(10)"`
		l := option.bufLen
		if l == 0 {
			l = 1
		}
		return zeroFill(w, l)

	case Ignore: // ignoring value: `binary:"ignore"`
		return 0, nil

	case iInvalid:
		err = ErrInvalidType
		return
	}

	// based on kind group
	switch encodeType.iKind() {

	case intKind, uintKind, bitmapKind, floatKind:
		return ms.writeScalar(w, order, v, encodeType)

	case structKind:
		return ms.writeStruct(w, order, v)

	case stringKind:
		return ms.writeString(w, order, v, encodeType, option.bufLen, option.encoding)
	}

	err = fmt.Errorf("unknown type %s", encodeType)
	return
}

// write an array
func (ms *Marshaler) writeArray(w io.Writer, order ByteOrder, array reflect.Value, elementType eType, option typeOption) (n int, err error) {

	arrayKind := array.Kind()
	//
	// Go arrays and slices are primary target of array notation.
	//	a []int	`binary:"[10]byte"`
	// And there is a special case for string.
	//	s string `binary:"[10]uint16"`	// each string byte is converted to uint16
	// An exceptional case is that the target type is string array and given value is a string.
	//	s string `binary:"[3]zstring(0x10)"`	// s is writen as first string, and the others will be blank string
	//
	if arrayKind == reflect.String && elementType.iKind() != stringKind {
		// convert string to byte slice
		array = array.Convert(byteSliceType)
		arrayKind = array.Kind()
	}

	arrayLen := 1
	if arrayKind == reflect.Array || arrayKind == reflect.Slice {
		arrayLen = array.Len()
	}

	desiredLen := option.arrayLen
	if desiredLen <= 0 {
		desiredLen = arrayLen
	}
	if desiredLen < arrayLen {
		err = fmt.Errorf("array too large to fit: len %d, size %d", desiredLen, arrayLen)
		return
		// arrayLen = desiredLen
	}

	wErr := func(i int, e error) error {
		return fmt.Errorf("array index [%d]: %w", i, e)
	}
	var m int
	for i := 0; i < arrayLen; i++ {
		var e reflect.Value
		if arrayKind == reflect.Array || arrayKind == reflect.Slice {
			e = array.Index(i)
		} else {
			e = array
		}
		if elementType == Any {
			m, err = ms.writeValue(w, order, e)
			if err != nil {
				err = wErr(i, err)
				return
			}
		} else {
			var o typeOption
			o.bufLen = option.bufLen     // option may contain inheritable values
			o.encoding = option.encoding // option may contain inheritable values
			m, err = ms.writeMain(w, order, e, elementType, o, reflect.Value{}, -1)
			if err != nil {
				err = wErr(i, err)
				return
			}
		}
		n += m
	}
	if arrayLen < desiredLen {
		// fill the leftover
		sz := option.bufLen // element length supplied
		if sz == 0 {
			sz = m // m holds the byte count of last written element
		}
		if sz == 0 {
			// guess byte size of the element type
			eType := array.Elem().Type()
			eKind := eType.Kind()
			for eKind == reflect.Ptr || eKind == reflect.Interface {
				eType = eType.Elem()
				eKind = eType.Kind()
			}
			sz = int(eType.Size())
		}

		// total size = element size * element count
		sz = sz * (desiredLen - arrayLen)

		// write blank bytes
		m, err = zeroFill(w, sz)
		n += m
		if err != nil {
			return
		}
	}
	return
}

// write a struct
func (ms *Marshaler) writeStruct(w io.Writer, order ByteOrder, strc reflect.Value) (n int, err error) {
	if strc.CanInterface() {
		val := strc.Interface()
		if mw, ok := val.(MarshalerContextWriter); ok {
			return mw.WriteBinaryWithMarshaler(ms, w, order)
		}
		if bw, ok := val.(BinaryWriter); ok {
			return bw.WriteBinary(w, order)
		}
		if bm, ok := val.(stdencoding.BinaryMarshaler); ok {
			var blob []byte
			blob, err = bm.MarshalBinary()
			if err != nil {
				return 0, err
			}
			return w.Write(blob)
		}
	}
	if strc.CanAddr() {
		addr := strc.Addr()
		if addr.CanInterface() {
			val := addr.Interface()
			if mw, ok := val.(MarshalerContextWriter); ok {
				return mw.WriteBinaryWithMarshaler(ms, w, order)
			}
			if bw, ok := val.(BinaryWriter); ok {
				return bw.WriteBinary(w, order)
			}
			if bm, ok := val.(stdencoding.BinaryMarshaler); ok {
				var blob []byte
				blob, err = bm.MarshalBinary()
				if err != nil {
					return 0, err
				}
				return w.Write(blob)
			}
		}
	}

	if !safeMode {
		return ms.unsafeWriteStruct(w, order, strc)
	}
	typ := strc.Type()
	meta, err := getStructMetadata(typ)
	if err != nil {
		return 0, err
	}
	wErr := func(i int, e error) error {
		f := typ.Field(i)
		return fmt.Errorf("field <%s>: %w", f.Name, e)
	}
	writeEval := ms.encodeExprEval(order, strc, meta)
	for _, fMeta := range meta.fields {
		if fMeta.ignore {
			continue
		}
		if fMeta.unexported {
			continue
		}
		if fMeta.fieldErr != nil && !fMeta.hasTag {
			err = wErr(fMeta.index, fMeta.fieldErr)
			return
		}

		fieldVal := strc.Field(fMeta.index)

		if fMeta.omittable {
			if fMeta.omittableExpr != "" {
				limit, errEval := evaluateTagValue(strc, fMeta.omittableExpr)
				if errEval == nil && n >= limit {
					break
				}
			}
			fKind := typ.Field(fMeta.index).Type.Kind()
			if (fKind == reflect.Ptr || fKind == reflect.Interface) && fieldVal.IsNil() {
				break
			}
		}

		naturalType, option, errF := ms.resolveFieldEncoding(fieldVal, fMeta, writeEval)
		if errF != nil {
			err = wErr(fMeta.index, errF)
			return
		}

		// valueof: replace the field's value with one computed from other
		// fields (emit-only; the source struct is never modified).
		if fMeta.valueofExpr != "" {
			computed, errV := ms.evalValueof(order, strc, meta, fMeta.valueofExpr)
			if errV != nil {
				err = wErr(fMeta.index, errV)
				return
			}
			fieldVal = synthIntValue(fieldVal, computed)
		}

		// const: emit the fixed value, ignoring the struct field (emit-only).
		if fMeta.hasConst {
			if fMeta.constIsBytes {
				fieldVal = synthBytesValue(fieldVal, fMeta.constBytes)
			} else {
				fieldVal = synthIntValue(fieldVal, int(fMeta.constInt))
			}
		}

		var m int
		m, err = ms.writeMain(w, order, fieldVal, naturalType, option, strc, fMeta.index)
		if err != nil {
			err = wErr(fMeta.index, err)
			return
		}
		n += m
	}
	return
}

// resolveFieldEncoding determines the binary encode type and options for a
// struct field from its metadata. Decode-side size expressions are evaluated
// through the supplied evalExpr strategy (which differs between the write path
// and bytelen() measurement). Errors are returned unwrapped for the caller to
// annotate. It does not apply valueof, which overrides the field's value rather
// than its type. Shared by the safe and unsafe encode paths and by measurement.
func (ms *Marshaler) resolveFieldEncoding(fieldVal reflect.Value, fMeta structFieldMetadata, evalExpr func(string) (int, error)) (naturalType eType, option typeOption, err error) {
	if fieldVal.IsValid() {
		naturalType, option = getNaturalType(fieldVal)
	}
	if !fMeta.hasTag {
		return
	}
	if naturalType == iInvalid && fMeta.encodeType != Pad && fMeta.encodeType != Ignore {
		if fMeta.fieldErr != nil {
			return naturalType, option, fMeta.fieldErr
		}
		return naturalType, option, fmt.Errorf("the field %s is not encodable", fMeta.name)
	}
	if fMeta.encodeType != Any {
		naturalType = fMeta.encodeType
	}
	if fMeta.isArray {
		option.isArray = true
		if fMeta.arrayLenExpr != "" {
			option.arrayLen, err = evalExpr(fMeta.arrayLenExpr)
			if err != nil {
				return
			}
			if option.arrayLen < 0 {
				return naturalType, option, errNegativeSize
			}
		}
	}
	if fMeta.bufLenExpr != "" {
		option.bufLen, err = evalExpr(fMeta.bufLenExpr)
		if err != nil {
			return
		}
		if option.bufLen < 0 {
			return naturalType, option, errNegativeSize
		}
	}
	if fMeta.encoding != "" {
		option.encoding = fMeta.encoding
	}
	if fMeta.endian != endianNone {
		option.endian = fMeta.endian
	}
	if fMeta.serializer != "" {
		option.serializer = fMeta.serializer
	}
	return
}

// encodeExprEval returns the write-path size-expression evaluator: it resolves
// referenced valueof fields to their computed values (not their ignored Go
// field values), so a target's size expression (e.g. [NameLen]byte) agrees with
// the valueof-computed length actually written to the stream.
func (ms *Marshaler) encodeExprEval(order ByteOrder, strc reflect.Value, meta *structMetadata) func(string) (int, error) {
	return func(expr string) (int, error) {
		return ms.evalEncodeExpr(order, strc, meta, expr)
	}
}

// evalEncodeExpr evaluates a size expression at ENCODE time, resolving any
// referenced valueof field to its computed value. Functions are not permitted
// in size expressions.
func (ms *Marshaler) evalEncodeExpr(order ByteOrder, strc reflect.Value, meta *structMetadata, expr string) (int, error) {
	tokens, err := tokenize(expr)
	if err != nil {
		return 0, err
	}
	base := fieldValueResolver(strc)
	p := &tagParser{
		tokens: tokens,
		strc:   strc,
		resolveIdent: func(name string) (int, error) {
			if fm, ok := meta.fieldByName(name); ok && fm.valueofExpr != "" {
				return ms.evalValueof(order, strc, meta, fm.valueofExpr)
			}
			return base(name)
		},
	}
	v, err := p.parseExpr()
	if err != nil {
		return 0, err
	}
	if p.peek().typ != tokEOF {
		return 0, fmt.Errorf("unexpected token at end of expression: %s", p.peek().val)
	}
	return v, nil
}

// evalValueof evaluates a valueof expression at encode time, resolving
// bytelen()/count() against the live struct value.
func (ms *Marshaler) evalValueof(order ByteOrder, strc reflect.Value, meta *structMetadata, expr string) (int, error) {
	tokens, err := tokenize(expr)
	if err != nil {
		return 0, err
	}
	p := &tagParser{
		tokens:       tokens,
		strc:         strc,
		resolveIdent: fieldValueResolver(strc),
		callFunc: func(fn, arg string) (int, error) {
			return ms.evalValueofFunc(order, strc, meta, fn, arg)
		},
	}
	v, err := p.parseExpr()
	if err != nil {
		return 0, err
	}
	if p.peek().typ != tokEOF {
		return 0, fmt.Errorf("unexpected token at end of valueof expression: %s", p.peek().val)
	}
	return v, nil
}

// evalValueofFunc computes bytelen(field) or count(field).
func (ms *Marshaler) evalValueofFunc(order ByteOrder, strc reflect.Value, meta *structMetadata, fn, arg string) (int, error) {
	fMeta, ok := meta.fieldByName(arg)
	if !ok {
		return 0, fmt.Errorf("valueof: no field named %s", arg)
	}
	fieldVal := strc.Field(fMeta.index)

	switch fn {
	case "count":
		v := derefValue(fieldVal)
		switch v.Kind() {
		case reflect.Slice, reflect.Array:
			return v.Len(), nil
		default:
			return 0, fmt.Errorf("count(%s): field is not a slice or array (use bytelen for a string's byte length)", arg)
		}
	case "bytelen":
		return ms.fieldEncodedSize(order, strc, fieldVal, fMeta)
	default:
		return 0, fmt.Errorf("unknown function %s", fn)
	}
}

// fieldEncodedSize returns the number of bytes the field would occupy when
// encoded. It measures by encoding into a scratch buffer using the same logic
// as the real write, so it is exact for text-encoded strings and nested
// structs. (A fast path for fixed-width fields is a possible future
// optimization; correctness is preferred here over avoiding the second encode.)
func (ms *Marshaler) fieldEncodedSize(order ByteOrder, strc, fieldVal reflect.Value, fMeta structFieldMetadata) (int, error) {
	// Measurement strategy: honor constant sizes (e.g. string(16), [4]byte) but
	// use the value's own length for field-referencing expressions. This makes
	// bytelen() measure the field's actual content and avoids infinite recursion
	// when a length field's valueof references the very slice/string it sizes
	// (the canonical [NameLen]byte / valueof=bytelen(Name) pair).
	naturalEval := func(expr string) (int, error) {
		refs, _, e := exprReferences(expr)
		if e != nil {
			return 0, e
		}
		if len(refs) == 0 {
			return evaluateTagValue(reflect.Value{}, expr) // constant size
		}
		v := derefValue(fieldVal)
		switch v.Kind() {
		case reflect.Slice, reflect.Array, reflect.Map:
			// writeMain treats arrayLen==0 as "no elements", so the natural
			// element count must be supplied explicitly.
			return v.Len(), nil
		case reflect.String:
			// bufLen==0 makes writeString emit the full encoded form with no
			// padding, which is the exact encoded byte length (correct even for
			// multibyte text encodings like Shift-JIS).
			return 0, nil
		}
		return 0, nil
	}
	naturalType, option, err := ms.resolveFieldEncoding(fieldVal, fMeta, naturalEval)
	if err != nil {
		return 0, err
	}
	var buf bytes.Buffer
	n, err := ms.writeMain(&buf, order, fieldVal, naturalType, option, strc, fMeta.index)
	if err != nil {
		return 0, err
	}
	return n, nil
}

// synthIntValue builds a reflect.Value holding v, typed like orig when orig is
// an integer kind, otherwise a plain int (which the scalar writer converts to
// the field's encode type).
func synthIntValue(orig reflect.Value, v int) reflect.Value {
	if orig.IsValid() {
		switch orig.Kind() {
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
			nv := reflect.New(orig.Type()).Elem()
			nv.SetInt(int64(v))
			return nv
		case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
			nv := reflect.New(orig.Type()).Elem()
			nv.SetUint(uint64(v))
			return nv
		}
	}
	return reflect.ValueOf(v)
}

// synthBytesValue returns a value of orig's type holding the given bytes, used
// to emit a byte-sequence const without mutating the source field. orig may be
// a string, a byte slice, or a fixed byte array; len(b) is guaranteed to match
// a fixed array's length by const metadata validation.
func synthBytesValue(orig reflect.Value, b []byte) reflect.Value {
	if orig.IsValid() {
		switch orig.Kind() {
		case reflect.String:
			nv := reflect.New(orig.Type()).Elem()
			nv.SetString(string(b))
			return nv
		case reflect.Slice:
			nv := reflect.MakeSlice(orig.Type(), len(b), len(b))
			reflect.Copy(nv, reflect.ValueOf(b))
			return nv
		case reflect.Array:
			nv := reflect.New(orig.Type()).Elem()
			reflect.Copy(nv, reflect.ValueOf(b))
			return nv
		}
	}
	return reflect.ValueOf(b)
}

// derefValue follows pointers and interfaces to the underlying value.
func derefValue(v reflect.Value) reflect.Value {
	for v.Kind() == reflect.Ptr || v.Kind() == reflect.Interface {
		if v.IsNil() {
			break
		}
		v = v.Elem()
	}
	return v
}

// EncodeText encodes a string with installed encoding.
func (ms *Marshaler) EncodeText(utf8 []byte, textEncoding string) (encoded []byte, err error) {
	if textEncoding == "" {
		encoded = utf8
		return
	}
	var ec *encoding.Encoder
	if ms.encoderCache != nil {
		ec = ms.encoderCache[textEncoding]
	}
	if ec == nil {
		if ms.TextEncoding != nil {
			ec = ms.TextEncoding[textEncoding].NewEncoder()
		}
		if ec == nil {
			err = fmt.Errorf("unknown text encoding %s", textEncoding)
			return
		}
		if ms.encoderCache == nil {
			ms.encoderCache = make(map[string]*encoding.Encoder)
		}
		ms.encoderCache[textEncoding] = ec
	}
	return ec.Bytes(utf8)
}

// DecodeText decodes a string with installed encoding.
func (ms *Marshaler) DecodeText(encoded []byte, textEncoding string) (utf8 []byte, err error) {
	if textEncoding == "" {
		utf8 = encoded
		return
	}
	var dc *encoding.Decoder
	if ms.decoderCache != nil {
		dc = ms.decoderCache[textEncoding]
	}
	if dc == nil {
		if ms.TextEncoding != nil {
			dc = ms.TextEncoding[textEncoding].NewDecoder()
		}
		if dc == nil {
			err = fmt.Errorf("unknown text encoding %s", textEncoding)
			return
		}
		if ms.decoderCache == nil {
			ms.decoderCache = make(map[string]*encoding.Decoder)
		}
		ms.decoderCache[textEncoding] = dc
	}
	return dc.Bytes(encoded)
}

// write string types
func (ms *Marshaler) writeString(w io.Writer, order ByteOrder, v reflect.Value, encodeType eType, bufLen int, textEncoding string) (n int, err error) {
	s := v.String()
	stringBytes := []byte(s)

	var m int

	// process text encoding
	if textEncoding == "" {
		textEncoding = ms.DefaultTextEncoding
	}
	if textEncoding != "" {
		stringBytes, err = ms.EncodeText(stringBytes, textEncoding)
		if err != nil {
			return
		}
	}

	strlen := len(stringBytes)
	if bufLen <= 0 {
		bufLen = strlen
	}
	if bufLen < strlen {
		err = fmt.Errorf("string too long: len %d, buffer size %d", strlen, bufLen)
		return
	}

	// write string length
	maxlen, headersz := uint64(math.MaxInt64), 0
	switch encodeType {
	case Bstring:
		maxlen, headersz = math.MaxUint8, 1
	case Wstring:
		maxlen, headersz = math.MaxUint16, 2
	case Dwstring:
		maxlen, headersz = math.MaxUint32, 4
	}
	if uint64(bufLen) > maxlen {
		err = fmt.Errorf("string too long: len %d, max %d", strlen, maxlen)
		return
	}

	if headersz > 0 {
		// write string size header
		m, err = writeU64(w, order, uint64(strlen), headersz)
		n += m
		if err != nil {
			return
		}
	}

	// write string bytes
	m, err = w.Write(stringBytes)
	n += m
	if err != nil {
		return
	}

	// write terminating zero
	switch encodeType {
	case Zstring:
		w.Write(terminatingZeros[:1])
		n += 1
		m += 1
	case Z16string:
		w.Write(terminatingZeros[:2])
		n += 2
		m += 2
		//case Z32string:
		//	w.Write(terminatingZeros[:4])
	}

	if m < bufLen {
		// fill the leftovers
		m, err = zeroFill(w, bufLen-m)
		n += m
		if err != nil {
			return
		}
		return
	}

	return
}

// write a scalar value
func (ms *Marshaler) writeScalar(w io.Writer, order ByteOrder, v reflect.Value, k eType) (n int, err error) {
	enc := encodeFunc(v.Type(), k)
	if enc == nil {
		err = ErrInvalidType
		return
	}
	u64, sz, err := enc(v)
	if err != nil {
		return
	}
	return writeU64(w, order, u64, sz)
}

// write bytes according to the byte order
func writeU64(w io.Writer, order ByteOrder, u64 uint64, bytesize int) (n int, err error) {
	var buf [8]byte
	b := buf[:bytesize]
	switch bytesize {
	case 1:
		b[0] = byte(u64)
	case 2:
		order.PutUint16(b, uint16(u64))
	case 4:
		order.PutUint32(b, uint32(u64))
	case 8:
		order.PutUint64(b, u64)
	default:
		panic("invalid byte size")
	}
	return w.Write(b)
}

// write blank padding bytes
func zeroFill(w io.Writer, sz int) (n int, err error) {
	maxBufSize := 16384
	bsz := sz
	if bsz > maxBufSize {
		bsz = maxBufSize
	}
	buf := make([]byte, bsz)
	var m int
	for sz > 0 {
		if sz > maxBufSize {
			m, err = w.Write(buf)
		} else {
			m, err = w.Write(buf[:sz])
		}
		n += m
		sz -= m
		if err != nil {
			return
		}
	}
	return
}

var (
	terminatingZeros = []byte{0, 0, 0, 0}
)

// BinaryWriter is implemented by types that can serialize themselves to a stream.
type BinaryWriter interface {
	WriteBinary(w io.Writer, order ByteOrder) (int, error)
}

// MarshalerContextWriter is implemented by types that can serialize themselves to a stream using a Marshaler context.
type MarshalerContextWriter interface {
	WriteBinaryWithMarshaler(ms *Marshaler, w io.Writer, order ByteOrder) (int, error)
}
