// Code generated by binarystruct-codegen. DO NOT EDIT.

package example

import (
	"bytes"
	"fmt"
	"github.com/mixcode/binarystruct"
	"io"
)

// MarshalBinary implements encoding.BinaryMarshaler.
func (s *Packet) MarshalBinary() ([]byte, error) {
	var b bytes.Buffer
	_, err := s.WriteBinary(&b, binarystruct.BigEndian)
	return b.Bytes(), err
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (s *Packet) UnmarshalBinary(data []byte) error {
	r := bytes.NewReader(data)
	_, err := s.ReadBinary(r, binarystruct.BigEndian)
	return err
}

// WriteBinary implements binarystruct.BinaryWriter.
func (s *Packet) WriteBinary(w io.Writer, order binarystruct.ByteOrder) (int, error) {
	return s.WriteBinaryWithMarshaler(nil, w, order)
}

// WriteBinaryWithMarshaler implements binarystruct.MarshalerContextWriter.
func (s *Packet) WriteBinaryWithMarshaler(ms *binarystruct.Marshaler, w io.Writer, order binarystruct.ByteOrder) (n int, err error) {
	var tmp [8]byte
	var m int
	{
		writeLen := int(4)
		strBytes := make([]byte, writeLen)
		copy(strBytes, s.Magic)
		m, err = w.Write(strBytes)
		n += m
		if err != nil {
			return n, err
		}
	}
	order.PutUint32(tmp[:4], uint32(s.Seq))
	m, err = w.Write(tmp[:4])
	n += m
	if err != nil {
		return n, err
	}
	tmp[0] = byte(s.Version)
	m, err = w.Write(tmp[:1])
	n += m
	if err != nil {
		return n, err
	}
	{
		writeLen := int(8)
		m, err = w.Write(s.Payload[:writeLen])
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// ReadBinary implements binarystruct.BinaryReader.
func (s *Packet) ReadBinary(r io.Reader, order binarystruct.ByteOrder) (int, error) {
	return s.ReadBinaryWithMarshaler(nil, r, order)
}

// ReadBinaryWithMarshaler implements binarystruct.MarshalerContextReader.
func (s *Packet) ReadBinaryWithMarshaler(ms *binarystruct.Marshaler, r io.Reader, order binarystruct.ByteOrder) (n int, err error) {
	var tmp [8]byte
	var m int
	{
		readLen := int(4)
		strBytes := make([]byte, readLen)
		m, err = io.ReadFull(r, strBytes)
		n += m
		if err != nil {
			return n, err
		}
		strlen := len(strBytes)
		for ; strlen > 0 && strBytes[strlen-1] == 0; strlen-- {
		}
		s.Magic = string(strBytes[:strlen])
	}
	m, err = io.ReadFull(r, tmp[:4])
	n += m
	if err != nil {
		return n, err
	}
	s.Seq = uint32(order.Uint32(tmp[:4]))
	m, err = io.ReadFull(r, tmp[:1])
	n += m
	if err != nil {
		return n, err
	}
	s.Version = uint8(tmp[0])
	if s.Version < 1 {
		return n, fmt.Errorf("field Version: value %v is out of range [1..10]: %w", s.Version, binarystruct.ErrValidationError)
	}
	if s.Version > 10 {
		return n, fmt.Errorf("field Version: value %v is out of range [1..10]: %w", s.Version, binarystruct.ErrValidationError)
	}
	{
		readLen := int(8)
		s.Payload = make([]byte, readLen)
		m, err = io.ReadFull(r, s.Payload)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}
