// Code generated by binarystruct-codegen. DO NOT EDIT.

package example

import (
	"bytes"
	"github.com/mixcode/binarystruct"
	"io"
)

// MarshalBinary implements encoding.BinaryMarshaler.
func (s *Samples) MarshalBinary() ([]byte, error) {
	var b bytes.Buffer
	_, err := s.WriteBinary(&b, binarystruct.LittleEndian)
	return b.Bytes(), err
}

// AppendBinary implements encoding.BinaryAppender.
func (s *Samples) AppendBinary(b []byte) ([]byte, error) {
	buf := bytes.NewBuffer(b)
	_, err := s.WriteBinary(buf, binarystruct.LittleEndian)
	return buf.Bytes(), err
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler.
func (s *Samples) UnmarshalBinary(data []byte) error {
	r := bytes.NewReader(data)
	_, err := s.ReadBinary(r, binarystruct.LittleEndian)
	return err
}

// WriteBinary implements binarystruct.BinaryWriter.
func (s *Samples) WriteBinary(w io.Writer, order binarystruct.ByteOrder) (int, error) {
	return s.WriteBinaryWithMarshaler(nil, w, order)
}

// WriteBinaryWithMarshaler implements binarystruct.MarshalerContextWriter.
func (s *Samples) WriteBinaryWithMarshaler(ms *binarystruct.Marshaler, w io.Writer, order binarystruct.ByteOrder) (n int, err error) {
	order = binarystruct.LittleEndian
	var tmp [8]byte
	var m int
	order.PutUint32(tmp[:4], uint32((len(s.V))))
	m, err = w.Write(tmp[:4])
	n += m
	if err != nil {
		return n, err
	}
	{
		writeLen := int((len(s.V)))
		sbuf := make([]byte, writeLen*4)
		for i := 0; i < writeLen; i++ {
			order.PutUint32(sbuf[i*4:], uint32(s.V[i]))
		}
		m, err = w.Write(sbuf)
		n += m
		if err != nil {
			return n, err
		}
	}
	return n, nil
}

// ReadBinary implements binarystruct.BinaryReader.
func (s *Samples) ReadBinary(r io.Reader, order binarystruct.ByteOrder) (int, error) {
	return s.ReadBinaryWithMarshaler(nil, r, order)
}

// ReadBinaryWithMarshaler implements binarystruct.MarshalerContextReader.
func (s *Samples) ReadBinaryWithMarshaler(ms *binarystruct.Marshaler, r io.Reader, order binarystruct.ByteOrder) (n int, err error) {
	order = binarystruct.LittleEndian
	var tmp [8]byte
	var m int
	m, err = io.ReadFull(r, tmp[:4])
	n += m
	if err != nil {
		return n, err
	}
	s.N = uint32(order.Uint32(tmp[:4]))
	{
		readLen := int(s.N)
		s.V = make([]uint32, readLen)
		sbuf := make([]byte, readLen*4)
		m, err = io.ReadFull(r, sbuf)
		n += m
		if err != nil {
			return n, err
		}
		for i := 0; i < readLen; i++ {
			s.V[i] = uint32(order.Uint32(sbuf[i*4:]))
		}
	}
	return n, nil
}
