// Copyright 2026 github.com/mixcode

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/ioutil"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

type Generator struct {
	Dir          string
	Types        []string
	IncludeTests bool
}

type parsedFieldTag struct {
	hasTag       bool
	binaryType   string
	isArray      bool
	arrayLenExpr string
	bufLenExpr   string
	options      map[string]string
}

var mTag = regexp.MustCompile(`^\s*(\[([^\]]*)\])?([^\s\(\)]*)(\(([^\)]+)\))?`)

func parseFieldTag(tag *ast.BasicLit) parsedFieldTag {
	res := parsedFieldTag{options: make(map[string]string)}
	if tag == nil {
		return res
	}
	tagVal, err := strconv.Unquote(tag.Value)
	if err != nil {
		return res
	}
	re := regexp.MustCompile(`binary:"([^"]*)"`)
	m := re.FindStringSubmatch(tagVal)
	if len(m) < 2 {
		return res
	}
	res.hasTag = true
	tagStr, err := strconv.Unquote("\"" + m[1] + "\"")
	if err != nil {
		tagStr = m[1]
	}

	tags := strings.Split(tagStr, ",")
	if len(tags) == 0 || tags[0] == "" {
		return res
	}

	match := mTag.FindStringSubmatch(tags[0])
	if len(match) >= 6 {
		res.isArray = match[1] != ""
		res.arrayLenExpr = match[2]
		res.binaryType = match[3]
		res.bufLenExpr = match[5]
	}

	for _, opt := range tags[1:] {
		parts := strings.SplitN(opt, "=", 2)
		val := ""
		if len(parts) > 1 {
			val = parts[1]
		}
		res.options[parts[0]] = val
	}

	return res
}

func getGoTypeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return getGoTypeName(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + getGoTypeName(t.X)
	case *ast.ArrayType:
		if t.Len == nil {
			return "[]" + getGoTypeName(t.Elt)
		}
		var buf bytes.Buffer
		format.Node(&buf, token.NewFileSet(), t.Len)
		return "[" + buf.String() + "]" + getGoTypeName(t.Elt)
	default:
		return ""
	}
}

func translateExpression(expr string) string {
	if expr == "" {
		return ""
	}
	re := regexp.MustCompile(`[a-zA-Z_][a-zA-Z0-9_\.]*`)
	return re.ReplaceAllStringFunc(expr, func(s string) string {
		if s == "true" || s == "false" || s == "nil" {
			return s
		}
		return "s." + s
	})
}

func (g *Generator) Generate(outPath string) error {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, g.Dir, func(fi os.FileInfo) bool {
		if fi.Name() == filepath.Base(outPath) {
			return false
		}
		if strings.HasSuffix(fi.Name(), "_test.go") {
			return g.IncludeTests
		}
		return true
	}, 0)
	if err != nil {
		return fmt.Errorf("failed to parse directory: %w", err)
	}

	if len(pkgs) == 0 {
		return fmt.Errorf("no Go packages found in %s", g.Dir)
	}

	var pkg *ast.Package
	var pkgName string
	for name, p := range pkgs {
		pkg = p
		pkgName = name
		break
	}

	structs := make(map[string]*ast.StructType)
	for _, file := range pkg.Files {
		ast.Inspect(file, func(n ast.Node) bool {
			ts, ok := n.(*ast.TypeSpec)
			if !ok {
				return true
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				return true
			}
			structs[ts.Name.Name] = st
			return true
		})
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by binarystruct-codegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	needMath := false
	needRegexp := false
	needErrors := false
	needFmt := false

	for _, typeName := range g.Types {
		st, ok := structs[typeName]
		if !ok {
			return fmt.Errorf("type %s not found in package %s", typeName, pkgName)
		}
		for _, field := range st.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			goType := getGoTypeName(field.Type)
			parsedTag := parseFieldTag(field.Tag)
			binType := getEffectiveBinaryType(parsedTag.binaryType, goType)

			if binType == "float32" || binType == "float64" {
				needMath = true
			}
			if _, ok := parsedTag.options["match"]; ok {
				needRegexp = true
				needFmt = true
			}
			if _, ok := parsedTag.options["range"]; ok {
				needFmt = true
			}
			if val, ok := parsedTag.options["serializer"]; ok && val != "" {
				needErrors = true
				needFmt = true
			}
			if parsedTag.isArray && parsedTag.arrayLenExpr == "" {
				needErrors = true
			}
		}
	}

	buf.WriteString("import (\n")
	buf.WriteString("\t\"bytes\"\n")
	if needErrors {
		buf.WriteString("\t\"errors\"\n")
	}
	if needFmt {
		buf.WriteString("\t\"fmt\"\n")
	}
	buf.WriteString("\t\"io\"\n")
	if needMath {
		buf.WriteString("\t\"math\"\n")
	}
	if needRegexp {
		buf.WriteString("\t\"regexp\"\n")
	}
	buf.WriteString("\t\"github.com/mixcode/binarystruct\"\n")
	buf.WriteString(")\n\n")

	// Generate regex variables for match checks
	for _, typeName := range g.Types {
		st, ok := structs[typeName]
		if !ok {
			return fmt.Errorf("type %s not found in package %s", typeName, pkgName)
		}
		for _, field := range st.Fields.List {
			if len(field.Names) == 0 {
				continue
			}
			fieldName := field.Names[0].Name
			parsedTag := parseFieldTag(field.Tag)
			if pattern, ok := parsedTag.options["match"]; ok {
				fmt.Fprintf(&buf, "var regex_%s_%s = regexp.MustCompile(`%s`)\n", typeName, fieldName, pattern)
			}
		}
	}
	buf.WriteString("\n")

	for _, typeName := range g.Types {
		st := structs[typeName]
		if err := g.generateMethods(&buf, typeName, st); err != nil {
			return err
		}
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Dump unformatted code for debugging
		ioutil.WriteFile(outPath, buf.Bytes(), 0644)
		return fmt.Errorf("failed to format generated source: %w", err)
	}

	return ioutil.WriteFile(outPath, formatted, 0644)
}

func (g *Generator) generateMethods(buf *bytes.Buffer, typeName string, st *ast.StructType) error {
	// Write standard helper functions
	fmt.Fprintf(buf, "// MarshalBinary implements encoding.BinaryMarshaler.\n")
	fmt.Fprintf(buf, "func (s *%s) MarshalBinary() ([]byte, error) {\n", typeName)
	buf.WriteString("\tvar b bytes.Buffer\n")
	buf.WriteString("\t_, err := s.WriteBinary(&b, binarystruct.BigEndian)\n")
	buf.WriteString("\treturn b.Bytes(), err\n")
	buf.WriteString("}\n\n")

	fmt.Fprintf(buf, "// UnmarshalBinary implements encoding.BinaryUnmarshaler.\n")
	fmt.Fprintf(buf, "func (s *%s) UnmarshalBinary(data []byte) error {\n", typeName)
	buf.WriteString("\tr := bytes.NewReader(data)\n")
	buf.WriteString("\t_, err := s.ReadBinary(r, binarystruct.BigEndian)\n")
	buf.WriteString("\treturn err\n")
	buf.WriteString("}\n\n")

	// 1. WriteBinary (Standard)
	fmt.Fprintf(buf, "// WriteBinary implements binarystruct.BinaryWriter.\n")
	fmt.Fprintf(buf, "func (s *%s) WriteBinary(w io.Writer, order binarystruct.ByteOrder) (int, error) {\n", typeName)
	buf.WriteString("\treturn s.WriteBinaryWithMarshaller(nil, w, order)\n")
	buf.WriteString("}\n\n")

	// 2. WriteBinaryWithMarshaller (Context-aware)
	fmt.Fprintf(buf, "// WriteBinaryWithMarshaller implements binarystruct.MarshallerContextWriter.\n")
	fmt.Fprintf(buf, "func (s *%s) WriteBinaryWithMarshaller(ms *binarystruct.Marshaller, w io.Writer, order binarystruct.ByteOrder) (n int, err error) {\n", typeName)
	buf.WriteString("\tvar tmp [8]byte\n")
	buf.WriteString("\tvar m int\n")

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		fieldName := field.Names[0].Name
		goType := getGoTypeName(field.Type)
		parsedTag := parseFieldTag(field.Tag)

		if _, ok := parsedTag.options["ignore"]; ok || parsedTag.binaryType == "-" {
			continue
		}

		// Handle omittable with expression
		if omittableExpr, ok := parsedTag.options["omittable"]; ok && omittableExpr != "" {
			fmt.Fprintf(buf, "\tif n >= int(%s) {\n\t\treturn n, nil\n\t}\n", translateExpression(omittableExpr))
		} else if ok && strings.HasPrefix(goType, "*") {
			// EOF-based omission (pointer)
			fmt.Fprintf(buf, "\tif s.%s == nil {\n\t\treturn n, nil\n\t}\n", fieldName)
		}

		binType := getEffectiveBinaryType(parsedTag.binaryType, goType)

		if parsedTag.isArray {
			g.generateArrayWrite(buf, fieldName, goType, binType, parsedTag)
		} else {
			g.generateFieldWrite(buf, "s."+fieldName, goType, binType, parsedTag)
		}
	}
	buf.WriteString("\treturn n, nil\n")
	buf.WriteString("}\n\n")

	// 3. ReadBinary (Standard)
	fmt.Fprintf(buf, "// ReadBinary implements binarystruct.BinaryReader.\n")
	fmt.Fprintf(buf, "func (s *%s) ReadBinary(r io.Reader, order binarystruct.ByteOrder) (int, error) {\n", typeName)
	buf.WriteString("\treturn s.ReadBinaryWithMarshaller(nil, r, order)\n")
	buf.WriteString("}\n\n")

	// 4. ReadBinaryWithMarshaller (Context-aware)
	fmt.Fprintf(buf, "// ReadBinaryWithMarshaller implements binarystruct.MarshallerContextReader.\n")
	fmt.Fprintf(buf, "func (s *%s) ReadBinaryWithMarshaller(ms *binarystruct.Marshaller, r io.Reader, order binarystruct.ByteOrder) (n int, err error) {\n", typeName)
	buf.WriteString("\tvar tmp [8]byte\n")
	buf.WriteString("\tvar m int\n")

	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue
		}
		fieldName := field.Names[0].Name
		goType := getGoTypeName(field.Type)
		parsedTag := parseFieldTag(field.Tag)

		if _, ok := parsedTag.options["ignore"]; ok || parsedTag.binaryType == "-" {
			continue
		}

		binType := getEffectiveBinaryType(parsedTag.binaryType, goType)

		// Handle omittable
		if omittableExpr, ok := parsedTag.options["omittable"]; ok {
			if omittableExpr != "" {
				fmt.Fprintf(buf, "\tif n >= int(%s) {\n\t\treturn n, nil\n\t}\n", translateExpression(omittableExpr))
			} else {
				// EOF-based omission
				buf.WriteString("\t// EOF check for omittable\n")
				buf.WriteString("\t{\n")
				buf.WriteString("\t\tvar peek [1]byte\n")
				buf.WriteString("\t\t_, peekErr := io.ReadFull(r, peek[:])\n")
				buf.WriteString("\t\tif peekErr == io.EOF || peekErr == io.ErrUnexpectedEOF {\n")
				buf.WriteString("\t\t\treturn n, nil\n")
				buf.WriteString("\t\t}\n")
				buf.WriteString("\t\t// Restore the byte\n")
				buf.WriteString("\t\tr = io.MultiReader(bytes.NewReader(peek[:]), r)\n")
				buf.WriteString("\t}\n")
			}
		}

		if parsedTag.isArray {
			g.generateArrayRead(buf, fieldName, goType, binType, parsedTag, typeName)
		} else {
			g.generateFieldRead(buf, "s."+fieldName, goType, binType, parsedTag, typeName, fieldName)
		}
	}
	buf.WriteString("\treturn n, nil\n")
	buf.WriteString("}\n\n")

	return nil
}

func (g *Generator) generateFieldWrite(buf *bytes.Buffer, target, goType, binType string, parsedTag parsedFieldTag) {
	// Dereference pointer if necessary
	isPtr := strings.HasPrefix(goType, "*")
	accessor := target
	if isPtr {
		accessor = "*" + target
		fmt.Fprintf(buf, "\tif %s != nil {\n", target)
	}

	if val, ok := parsedTag.options["serializer"]; ok && val != "" {
		fmt.Fprintf(buf, "\tif ms == nil {\n\t\treturn n, errors.New(\"marshaller context required for custom serializer %s\")\n\t}\n", val)
		fmt.Fprintf(buf, "\t{\n\t\tser := ms.GetSerializer(%q)\n", val)
		buf.WriteString("\t\tif ser == nil {\n\t\t\treturn n, fmt.Errorf(\"unknown serializer: %s\", " + strconv.Quote(val) + ")\n\t\t}\n")
		fmt.Fprintf(buf, "\t\tm, err = ser.Serialize(w, %s, nil, -1, order)\n", accessor)
		buf.WriteString("\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n\t}\n")
		if isPtr {
			buf.WriteString("\t}\n")
		}
		return
	}

	switch binType {
	case "int8", "uint8", "byte":
		fmt.Fprintf(buf, "\ttmp[0] = byte(%s)\n", accessor)
		buf.WriteString("\tm, err = w.Write(tmp[:1])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
	case "int16", "uint16", "word":
		fmt.Fprintf(buf, "\torder.PutUint16(tmp[:2], uint16(%s))\n", accessor)
		buf.WriteString("\tm, err = w.Write(tmp[:2])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
	case "int32", "uint32", "dword":
		fmt.Fprintf(buf, "\torder.PutUint32(tmp[:4], uint32(%s))\n", accessor)
		buf.WriteString("\tm, err = w.Write(tmp[:4])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
	case "int64", "uint64", "qword":
		fmt.Fprintf(buf, "\torder.PutUint64(tmp[:8], uint64(%s))\n", accessor)
		buf.WriteString("\tm, err = w.Write(tmp[:8])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
	case "float32":
		fmt.Fprintf(buf, "\torder.PutUint32(tmp[:4], math.Float32bits(float32(%s)))\n", accessor)
		buf.WriteString("\tm, err = w.Write(tmp[:4])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
	case "float64":
		fmt.Fprintf(buf, "\torder.PutUint64(tmp[:8], math.Float64bits(float64(%s)))\n", accessor)
		buf.WriteString("\tm, err = w.Write(tmp[:8])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
	case "pad":
		sizeExpr := translateExpression(parsedTag.bufLenExpr)
		if sizeExpr == "" {
			sizeExpr = "1"
		}
		fmt.Fprintf(buf, "\t{\n\t\tm, err = w.Write(make([]byte, %s))\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n\t}\n", sizeExpr)
	case "string", "bstring", "wstring", "dwstring", "zstring", "z16string":
		encodingOpt := parsedTag.options["encoding"]
		fmt.Fprintf(buf, "\t{\n\t\tstrBytes := []byte(%s)\n", accessor)
		if encodingOpt != "" {
			fmt.Fprintf(buf, "\t\tif ms != nil {\n\t\t\tstrBytes, err = ms.EncodeText(strBytes, %q)\n\t\t\tif err != nil {\n\t\t\t\treturn n, err\n\t\t\t}\n\t\t}\n", encodingOpt)
		}
		// Write prefix for prefixed strings
		switch binType {
		case "bstring":
			buf.WriteString("\t\ttmp[0] = byte(len(strBytes))\n")
			buf.WriteString("\t\tm, err = w.Write(tmp[:1])\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
		case "wstring":
			buf.WriteString("\t\torder.PutUint16(tmp[:2], uint16(len(strBytes)))\n")
			buf.WriteString("\t\tm, err = w.Write(tmp[:2])\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
		case "dwstring":
			buf.WriteString("\t\torder.PutUint32(tmp[:4], uint32(len(strBytes)))\n")
			buf.WriteString("\t\tm, err = w.Write(tmp[:4])\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
		}
		// Pad or truncate string to buffer size
		if parsedTag.bufLenExpr != "" {
			bufSize := translateExpression(parsedTag.bufLenExpr)
			fmt.Fprintf(buf, "\t\tbufLen := int(%s)\n", bufSize)
			buf.WriteString("\t\twriteBytes := make([]byte, bufLen)\n")
			buf.WriteString("\t\tcopy(writeBytes, strBytes)\n")
			buf.WriteString("\t\tm, err = w.Write(writeBytes)\n")
		} else {
			buf.WriteString("\t\tm, err = w.Write(strBytes)\n")
		}
		buf.WriteString("\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
		// Write null termination
		if binType == "zstring" {
			buf.WriteString("\t\ttmp[0] = 0\n\t\tm, err = w.Write(tmp[:1])\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
		} else if binType == "z16string" {
			buf.WriteString("\t\torder.PutUint16(tmp[:2], 0)\n\t\tm, err = w.Write(tmp[:2])\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
		}
		buf.WriteString("\t}\n")
	default:
		// Nested struct or fallback
		fmt.Fprintf(buf, "\t{\n\t\tm, err = binarystruct.Write(w, order, &%s)\n", accessor)
		buf.WriteString("\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n\t}\n")
	}

	if isPtr {
		buf.WriteString("\t}\n")
	}
}

func (g *Generator) generateFieldRead(buf *bytes.Buffer, target, goType, binType string, parsedTag parsedFieldTag, typeName, fieldName string) {
	isPtr := strings.HasPrefix(goType, "*")
	accessor := target
	if isPtr {
		accessor = "val"
		fmt.Fprintf(buf, "\t{\n\t\tvar val %s\n", strings.TrimPrefix(goType, "*"))
	}

	if val, ok := parsedTag.options["serializer"]; ok && val != "" {
		fmt.Fprintf(buf, "\tif ms == nil {\n\t\treturn n, errors.New(\"marshaller context required for custom serializer %s\")\n\t}\n", val)
		fmt.Fprintf(buf, "\t{\n\t\tser := ms.GetSerializer(%q)\n", val)
		buf.WriteString("\t\tif ser == nil {\n\t\t\treturn n, fmt.Errorf(\"unknown serializer: %s\", " + strconv.Quote(val) + ")\n\t\t}\n")
		fmt.Fprintf(buf, "\t\tvalDec, m, err := ser.Deserialize(r, nil, -1, order)\n")
		buf.WriteString("\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
		fmt.Fprintf(buf, "\t\t%s = valDec.(%s)\n\t}\n", accessor, strings.TrimPrefix(goType, "*"))
	} else {
		switch binType {
		case "int8", "uint8", "byte":
			buf.WriteString("\tm, err = io.ReadFull(r, tmp[:1])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
			fmt.Fprintf(buf, "\t%s = %s(tmp[0])\n", accessor, strings.TrimPrefix(goType, "*"))
		case "int16", "uint16", "word":
			buf.WriteString("\tm, err = io.ReadFull(r, tmp[:2])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
			fmt.Fprintf(buf, "\t%s = %s(order.Uint16(tmp[:2]))\n", accessor, strings.TrimPrefix(goType, "*"))
		case "int32", "uint32", "dword":
			buf.WriteString("\tm, err = io.ReadFull(r, tmp[:4])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
			fmt.Fprintf(buf, "\t%s = %s(order.Uint32(tmp[:4]))\n", accessor, strings.TrimPrefix(goType, "*"))
		case "int64", "uint64", "qword":
			buf.WriteString("\tm, err = io.ReadFull(r, tmp[:8])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
			fmt.Fprintf(buf, "\t%s = %s(order.Uint64(tmp[:8]))\n", accessor, strings.TrimPrefix(goType, "*"))
		case "float32":
			buf.WriteString("\tm, err = io.ReadFull(r, tmp[:4])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
			fmt.Fprintf(buf, "\t%s = %s(math.Float32frombits(order.Uint32(tmp[:4])))\n", accessor, strings.TrimPrefix(goType, "*"))
		case "float64":
			buf.WriteString("\tm, err = io.ReadFull(r, tmp[:8])\n\tn += m\n\tif err != nil {\n\t\treturn n, err\n\t}\n")
			fmt.Fprintf(buf, "\t%s = %s(math.Float64frombits(order.Uint64(tmp[:8])))\n", accessor, strings.TrimPrefix(goType, "*"))
		case "pad":
			sizeExpr := translateExpression(parsedTag.bufLenExpr)
			if sizeExpr == "" {
				sizeExpr = "1"
			}
			fmt.Fprintf(buf, "\t{\n\t\tpadSize := int(%s)\n", sizeExpr)
			buf.WriteString("\t\tm, err = io.ReadFull(r, make([]byte, padSize))\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n\t}\n")
		case "string", "bstring", "wstring", "dwstring", "zstring", "z16string":
			encodingOpt := parsedTag.options["encoding"]
			buf.WriteString("\t{\n\t\tvar strBytes []byte\n")
			switch binType {
			case "bstring":
				buf.WriteString("\t\tm, err = io.ReadFull(r, tmp[:1])\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
				buf.WriteString("\t\tstrLen := int(tmp[0])\n")
				buf.WriteString("\t\tstrBytes = make([]byte, strLen)\n")
				buf.WriteString("\t\tm, err = io.ReadFull(r, strBytes)\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
			case "wstring":
				buf.WriteString("\t\tm, err = io.ReadFull(r, tmp[:2])\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
				buf.WriteString("\t\tstrLen := int(order.Uint16(tmp[:2]))\n")
				buf.WriteString("\t\tstrBytes = make([]byte, strLen)\n")
				buf.WriteString("\t\tm, err = io.ReadFull(r, strBytes)\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
			case "dwstring":
				buf.WriteString("\t\tm, err = io.ReadFull(r, tmp[:4])\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
				buf.WriteString("\t\tstrLen := int(order.Uint32(tmp[:4]))\n")
				buf.WriteString("\t\tstrBytes = make([]byte, strLen)\n")
				buf.WriteString("\t\tm, err = io.ReadFull(r, strBytes)\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
			case "zstring":
				buf.WriteString("\t\tfor {\n\t\t\tm, err = io.ReadFull(r, tmp[:1])\n\t\t\tn += m\n\t\t\tif err != nil {\n\t\t\t\treturn n, err\n\t\t\t}\n\t\t\tif tmp[0] == 0 {\n\t\t\t\tbreak\n\t\t\t}\n\t\t\tstrBytes = append(strBytes, tmp[0])\n\t\t}\n")
			case "z16string":
				buf.WriteString("\t\tfor {\n\t\t\tm, err = io.ReadFull(r, tmp[:2])\n\t\t\tn += m\n\t\t\tif err != nil {\n\t\t\t\treturn n, err\n\t\t\t}\n\t\t\tval := order.Uint16(tmp[:2])\n\t\t\tif val == 0 {\n\t\t\t\tbreak\n\t\t\t}\n\t\t\tstrBytes = append(strBytes, byte(val), byte(val>>8)) // UTF-16 bytes\n\t\t}\n")
			default:
				if parsedTag.bufLenExpr != "" {
					fmt.Fprintf(buf, "\t\tstrLen := int(%s)\n", translateExpression(parsedTag.bufLenExpr))
					buf.WriteString("\t\tstrBytes = make([]byte, strLen)\n")
					buf.WriteString("\t\tm, err = io.ReadFull(r, strBytes)\n\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
				} else {
					buf.WriteString("\t\t// Read all remaining\n\t\tstrBytes, err = io.ReadAll(r)\n\t\tn += len(strBytes)\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
				}
			}

			if encodingOpt != "" {
				fmt.Fprintf(buf, "\t\tif ms != nil {\n\t\t\tstrBytes, err = ms.DecodeText(strBytes, %q)\n\t\t\tif err != nil {\n\t\t\t\treturn n, err\n\t\t\t}\n\t\t}\n", encodingOpt)
			}
			// Remove trailing zeros
			buf.WriteString("\t\tstrlen := len(strBytes)\n")
			buf.WriteString("\t\tfor ; strlen > 0 && strBytes[strlen-1] == 0; strlen-- {}\n")
			fmt.Fprintf(buf, "\t\t%s = string(strBytes[:strlen])\n", accessor)
			buf.WriteString("\t}\n")
		default:
			// Nested struct
			fmt.Fprintf(buf, "\t{\n\t\tm, err = binarystruct.Read(r, order, &%s)\n", accessor)
			buf.WriteString("\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n\t}\n")
		}
	}

	// Apply range check if specified
	if rangeOpt, ok := parsedTag.options["range"]; ok {
		bounds := strings.Split(rangeOpt, "..")
		if len(bounds) == 2 {
			minStr := strings.TrimSpace(bounds[0])
			maxStr := strings.TrimSpace(bounds[1])
			if minStr != "" {
				fmt.Fprintf(buf, "\tif %s < %s {\n", accessor, minStr)
				fmt.Fprintf(buf, "\t\treturn n, fmt.Errorf(\"field %s: value %%v is out of range [%s..%s]: %%w\", %s, binarystruct.ErrValidationError)\n\t}\n", fieldName, minStr, maxStr, accessor)
			}
			if maxStr != "" {
				fmt.Fprintf(buf, "\tif %s > %s {\n", accessor, maxStr)
				fmt.Fprintf(buf, "\t\treturn n, fmt.Errorf(\"field %s: value %%v is out of range [%s..%s]: %%w\", %s, binarystruct.ErrValidationError)\n\t}\n", fieldName, minStr, maxStr, accessor)
			}
		}
	}

	// Apply regex match check
	if _, ok := parsedTag.options["match"]; ok {
		fmt.Fprintf(buf, "\tif !regex_%s_%s.MatchString(%s) {\n", typeName, fieldName, accessor)
		fmt.Fprintf(buf, "\t\treturn n, fmt.Errorf(\"field %s: value %%q does not match pattern: %%w\", %s, binarystruct.ErrValidationError)\n\t}\n", fieldName, accessor)
	}

	if isPtr {
		fmt.Fprintf(buf, "\t\t%s = &val\n\t}\n", target)
	}
}

func (g *Generator) generateArrayWrite(buf *bytes.Buffer, fieldName, goType, binType string, parsedTag parsedFieldTag) {
	sizeExpr := translateExpression(parsedTag.arrayLenExpr)
	if sizeExpr == "" {
		sizeExpr = fmt.Sprintf("len(s.%s)", fieldName)
	}

	if goType == "string" {
		if binType == "byte" || binType == "uint8" {
			fmt.Fprintf(buf, "\t{\n\t\twriteLen := int(%s)\n", sizeExpr)
			buf.WriteString("\t\tstrBytes := make([]byte, writeLen)\n")
			fmt.Fprintf(buf, "\t\tcopy(strBytes, s.%s)\n", fieldName)
			buf.WriteString("\t\tm, err = w.Write(strBytes)\n")
			buf.WriteString("\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n\t}\n")
			return
		}
	}

	// Bulk write optimization for byte slices
	if binType == "byte" || binType == "uint8" {
		fmt.Fprintf(buf, "\t{\n\t\twriteLen := int(%s)\n", sizeExpr)
		fmt.Fprintf(buf, "\t\tm, err = w.Write(s.%s[:writeLen])\n", fieldName)
		buf.WriteString("\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n\t}\n")
		return
	}

	fmt.Fprintf(buf, "\t{\n\t\tlimit := int(%s)\n", sizeExpr)
	buf.WriteString("\t\tfor i := 0; i < limit; i++ {\n")
	g.generateFieldWrite(buf, fmt.Sprintf("s.%s[i]", fieldName), strings.TrimPrefix(goType, "[]"), binType, parsedTag)
	buf.WriteString("\t\t}\n\t}\n")
}

func (g *Generator) generateArrayRead(buf *bytes.Buffer, fieldName, goType, binType string, parsedTag parsedFieldTag, typeName string) {
	sizeExpr := translateExpression(parsedTag.arrayLenExpr)
	if sizeExpr == "" {
		buf.WriteString("\treturn n, errors.New(\"unknown array size expression\")\n")
		return
	}

	if goType == "string" {
		if binType == "byte" || binType == "uint8" {
			fmt.Fprintf(buf, "\t{\n\t\treadLen := int(%s)\n", sizeExpr)
			buf.WriteString("\t\tstrBytes := make([]byte, readLen)\n")
			buf.WriteString("\t\tm, err = io.ReadFull(r, strBytes)\n")
			buf.WriteString("\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n")
			buf.WriteString("\t\tstrlen := len(strBytes)\n")
			buf.WriteString("\t\tfor ; strlen > 0 && strBytes[strlen-1] == 0; strlen-- {}\n")
			fmt.Fprintf(buf, "\t\ts.%s = string(strBytes[:strlen])\n", fieldName)
			buf.WriteString("\t}\n")
			return
		}
	}

	// Slice initialization
	fmt.Fprintf(buf, "\t{\n\t\treadLen := int(%s)\n", sizeExpr)
	fmt.Fprintf(buf, "\t\ts.%s = make(%s, readLen)\n", fieldName, goType)

	// Bulk read optimization for byte slices
	if binType == "byte" || binType == "uint8" {
		fmt.Fprintf(buf, "\t\tm, err = io.ReadFull(r, s.%s)\n", fieldName)
		buf.WriteString("\t\tn += m\n\t\tif err != nil {\n\t\t\treturn n, err\n\t\t}\n\t}\n")
		return
	}

	buf.WriteString("\t\tfor i := 0; i < readLen; i++ {\n")
	g.generateFieldRead(buf, fmt.Sprintf("s.%s[i]", fieldName), strings.TrimPrefix(goType, "[]"), binType, parsedTag, typeName, fmt.Sprintf("%s[i]", fieldName))
	buf.WriteString("\t\t}\n\t}\n")
}

func getEffectiveBinaryType(binType, goType string) string {
	if binType != "" && binType != "any" {
		return binType
	}
	goType = strings.TrimPrefix(goType, "*")
	goType = strings.TrimPrefix(goType, "[]")
	return goType
}
